app/controllers/company/views.py
from flask import Blueprint, request, render_template, \
    flash, g, session, redirect, url_for, jsonify, json
from flask_responses import json_response, xml_response, auto_response
from flask_paginate import Pagination, get_page_parameter, get_page_args

from app import db
from app.models.company_models import Company

company = Blueprint('company', __name__, url_prefix='/company')


@company.route('/', methods=['GET'])
def index():
    page, per_page, offset = get_page_args()
    data_count = Company.query.filter_by(deleted=False).count()
    data = Company.query.filter_by(
        deleted=False).limit(per_page).offset(offset)
    search = False
    print('data_count', data_count, per_page, offset)

    pagination = Pagination(page=page, total=data_count, search=search,
                            record_name='', per_page=per_page, css_framework='foundation')

    return render_template('company/index.html',
                           data=data,  pagination=pagination,
                           title='Барааны жагсаалт')


@company.route('/edit/<int:company_id>', methods=['GET'])
def edit(company_id):
    return jsonify('Editing! ' + str(company_id))


@company.route('/save', methods=['POST'])
def save(company_id):
    return jsonify('Saved! ' + str(company_id))

app/templates/partials/_footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Хувилбар</b> {{config_item('CMS_VERSION')}} </div>
    <strong>{{config_item('CMS_NAME')}} Хөгжүүлэгч ©
        <a href="http://odo.com">{{config_item('CMS_COMPANY')}}</a>.</strong> Бүх эрх хуулиар хамгаалагдсан.
</footer>

app/templates/partials/_header.html
<header class="main-header">

  <div class="logo-container">
    <span class="logo-collapse">ЦЭС</span>
    <div class="logo-extend">
      <a href="javascript:void(0);" id="toggler-sidebar">
        <i class="fa fa-bars"></i>
      </a>
      <a href="{{site_url()}}" class="logo">
        <span class="lo1">O</span>
        <span class="ld2">d</span>
        <span class="lo3">O</span>
        <span class="lv4">v{{config_item('CMS_VERSION')}}</span>
      </a>
    </div>
  </div>

  <nav class="navbar navbar-static-top">
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header"><h6>Танд 10 мэдэгдэл ирсэн байна.</h6></li>
            <li class="notif-body">
              <ul class="notif-list">
                <li>
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-user text-red"></i> You changed your username
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="javascript:void(0);">View all</a>
            </li>
          </ul>
        </li>


        {% set user_img_url = assets_url('img/avatar-blue.png') %}
        <li class="dropdown user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
            <img src="{{user_img_url}}" class="user-image" alt="User Image">
            <span class="hidden-xs">{{config_item('CMS_COMPANY')}}</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="header">
              <img src="{{user_img_url}}" class="img-avatar" alt="User Image">
              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <li class="footer">
              <div class="pull-left">
                <a href="#" class="btn btn-primary">Хувийн мэдээлэл</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-danger">Гарах</a>
              </div>
            </li>
          </ul>
        </li>

      </ul>
    </div>

  </nav>

</header>

app/templates/partials/_sidebar.html
<aside class="main-sidebar with-shadow">

    <section class="sidebar">
        
        <ul class="sidebar-menu">
            <li class="header">Үндсэн цэс</li>
            <li>
                <a href="app">
                    <i class="fa fa-dashboard fa-line-chart"></i>
                    <span>Хянах самбар</span>
                </a>
            </li>
            <li class="menuitem active">
                <a href="javascript:void(0);">
                    <i class="fa fa-adjust"></i>
                    <span>Удирдлага</span>
                    <span class="right-fa-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="menuitem-submenu">
                    <li>
                        <a href="{{url_for('company.index')}}">
                            <i class="fa fa-object-group"></i>
                            <span>Компани</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('company.index')}}">
                            <i class="fa fa-user-md"></i>
                            <span>Бараа</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('company.index')}}">
                            <i class="fa fa-paperclip"></i>
                            <span>Харилцагчид</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="menuitem active">
                <a href="javascript:void(0);">
                    <i class="fa fa-reorder"></i>
                    <span>Захиалга</span>
                    <span class="right-fa-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="menuitem-submenu">
                    <li>
                        <a href="app/lombard" title="Бараа татан авалт">
                            <i class="fa fa-list"></i>
                            <span>Бараа татан авалт</span>
                        </a>
                    </li>
                    <li>
                        <a href="app/lombard" title="Захиалгын хүсэлтүүд">
                            <i class="fa fa-list"></i>
                            <span>Захиалгын хүсэлтүүд</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="menuitem active">
                <a href="javascript:void(0);">
                    <i class="fa fa-shopping-bag"></i>
                    <span>Худалдаа</span>
                    <span class="right-fa-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="menuitem-submenu">
                    <li>
                        <a href="app/accstream" title="Худалдааны цэг">
                            <i class="fa fa-list"></i>
                            <span>ПОС</span>
                        </a>
                    </li>
                    <li>
                        <a href="app/accstream" title="Худалдааны тайлан">
                            <i class="fa fa-list"></i>
                            <span>Тайлан</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="menuitem">
                <a href="javascript:void(0);">
                    <i class="fa fa-folder"></i>
                    <span>Файлын сан</span>
                </a>
            </li>
            <li class="menuitem">
                <a href="javascript:void(0);">
                    <i class="fa fa-gears"></i>
                    <span>Систем</span>
                    <span class="right-fa-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="menuitem-submenu">
                    <li>
                        <a href="app/role" title="Системийн хандах эрхүүд">
                            <i class="fa fa-user-secret"></i>
                            <span>Системийн эрхүүд</span>
                        </a>
                    </li>
                    <li>
                        <a href="app/account" title="Системд бүртгэлтэй нийт хэрэглэгчдийг удирдах цонх">
                            <i class="fa fa-user"></i>
                            <span>Хэрэглэгч</span>
                        </a>
                    </li>
                    <li>
                        <a href="app/authortype" title="Дэлгүүр, Баар паб, Супермаркет гэх мэт">
                            <i class="fa fa-sticky-note-o"></i>
                            <span>Харилцагчийн төрөл</span>
                        </a>
                    </li>
                    <li>
                        <a href="app/author" title="Системд бүртгэлтэй нийт байгууллагуудыг удирдах цонх">
                            <i class="fa fa-sticky-note"></i>
                            <span>Нийт харилцагчид</span>
                        </a>
                    </li>
                    <li>
                        <a href="app/author" title="Системд бүртгэлтэй нийт бараануудыг удирдах цонх">
                            <i class="fa fa-sticky-note"></i>
                            <span>Нийт бараанууд</span>
                        </a>
                    </li>
                    <li>
                        <a href="app/setting" title="Системийн ерөнхий тохиргоо">
                            <i class="fa fa-gear"></i>
                            <span>Тохиргоо</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="visible">
                <a href="javascript:void(0);">
                    <i class="fa fa-book"></i>
                    <span>Тусламж</span>
                </a>
            </li>
            <li class="visible">
                <div class="gap25"></div>
            </li>
        </ul>
    </section>

</aside>